---
fixtures:
  repositories:
    logrotate: https://github.com/simp/pupmod-simp-logrotate
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib:  https://github.com/simp/puppetlabs-stdlib
  symlinks:
    openscap: "#{source_dir}"
