<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  el7:
    roles:
      - server7
      - default
    platform: el-7-x86_64
    box :     centos/7
    hypervisor : <%= hypervisor %>

  el6:
    roles:
      - server6
    platform: el-6-x86_64
    box :     centos/6
    hypervisor : <%= hypervisor %>
CONFIG:
  type: aio
  log_level: verbose
  vagrant_memsize: 256
  log_level: verbose
<% if ENV['BEAKER_PUPPET_ENVIRONMENT'] -%>
  puppet_environment: <%= ENV['BEAKER_PUPPET_ENVIRONMENT'] %>
<% end -%>
