<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  el7:
    roles:
      - default
    platform: el-7-x86_64
    box :     centos/7
    hypervisor : <%= hypervisor %>

  el6:
    platform: el-6-x86_64
    box :     centos/6
    hypervisor : <%= hypervisor %>

  el8:
    platform: el-8-x86_64
    box :     centos/8
    hypervisor : <%= hypervisor %>

CONFIG:
  type: aio
  log_level: verbose
  vagrant_memsize: 256
  log_level: verbose
<% if ENV['BEAKER_PUPPET_COLLECTION'] -%>
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] %>
<% end -%>
